### PR TITLE
Adds a Docker log source.

### PR DESCRIPTION
**Pull request by tommie**
Provides a cleaner split between log sources, specifically for not
compiling with systemd libraries.

This is in preparation for a new log source to read from Docker.

### CODE REVIEW

**Comment by jbguerraz** [comment]
Nice to see that @tommie ! :)
Is the docker source already usable ? would be happy to help with it anyway! (we're running the exporter in a container in same pod than postfix, but using some tricks to have postfix logs written in both the stdout and in some file for the exporter to be happy)

**Comment by tommie** [comment]
I'm using it, though it's just for a personal server. I'd be happy to have more eyes on it.

As for future improvements: It's obviously using the Docker socket, which might be sensitive. I'm running the exporter in its own container, and it doesn't have any exposed ports. That's fine for me, but a socket proxy with ACLs might be useful in other settings.

Other than that, I'm happy the way it is. I see there's now a conflict. I'll wait for maintainers to approve the PR in principle before spending more time on that.

I want my containers to have radonly file systems. Docker logs help with that.

**Comment by jbguerraz** [comment]
@tommie great!
FYI, at the moment we gently ask Postfix to write its logs in a named pipe, that is readed by `tee`, which output on both stdout for container logs and also on another named pipe which in turn is readed by the exporter. It's actually readonly (since kernel pass the data from pipe to pipe) but require to run a shell script in addition to postfix (and so, postfix isn't the only process in the container)

**Comment by tommie** [comment]
Ah, so you're also logging to Docker, and only using tee to support the exporter. Makes sense.

**Comment by BartVerc** [comment]
I like the way the LogSources are split this way. Thanks for the MR!

**Pull request merged**
