### PR TITLE
Expose standalone metric for number of messages per queue

### PR DESCRIPTION
**Pull request by zoni**
This commit adds a new gauge, "showq_message_count", containing the
total number of messages by queue.

It was already sort of possible to get this information by piggybacking
off of the message size and/or message age histograms, however the
downside of that approach is that when there are no messages in a given
queue, no metric is exported.

This new showq_message_count metric will instead export 0 when a given
queue contains no messages, allowing one to query instances where a
postfix queue is empty and preventing metrics from being considered
stale by Prometheus.

### CODE REVIEW

**Comment by BartVerc** [comment]
Isn't it possible to use Count(messages) per queue in Prometheus?

**Comment by zoni** [comment]
I'm not sure I quite follow. What do you mean exactly?

**Comment by BartVerc** [comment]
The metrics you added to the exporter can easily be calculated by prometheus. 
Query Count(postfix_showq_message_size_bytes) by (queue) for example.

**Comment by zoni** [comment]
Ah, no, unfortunately that doesn't work, as explained in the description of this PR:

> It was already sort of possible to get this information by piggybacking
> off of the message size and/or message age histograms, however the
> downside of that approach is that when there are no messages in a given
> queue, no metric is exported.
> 
> This new showq_message_count metric will instead export 0 when a given
> queue contains no messages, allowing one to query instances where a
> postfix queue is empty and preventing metrics from being considered
> stale by Prometheus.

My first attempt was to initialize the histograms so that even empty queues have a corresponding metric, but that doesn't appear to be possible. Calling `.Observe(0)` initially counts as an actual observation (obviously) so it increments the total by one, which is wrong, and there doesn't appear to be any other way to set an empty dimension on a histogram.

**Comment by BartVerc** [comment]
If we initialize the buckets to zero, the message count by queue can be calculated with:
`
Sum(postfix_showq_message_size_bytes_bucket) by (queue)`

Can you please take a look at this option:
https://github.com/kumina/postfix_exporter/pull/8

**Comment by BartVerc** [comment]
See https://github.com/kumina/postfix_exporter/pull/8, now the count metric is available for every queue that is initialized.

**Comment by zoni** [comment]
Nice. It was non-obvious to me from the documentation on `github.com/prometheus/client_golang/prometheus` that it could be done this way. 😃 I can confirm #8 works as intended and should probably be merged in favor of this one.

**Comment by BartVerc** [comment]
Solved in https://github.com/kumina/postfix_exporter/pull/8.

**Pull request closed without merging**
