### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by flyhard**
Did a big refactoring:
- new gauge counting the lines we have processed
- Showq is polling every 10 seconds - configurable via command line flag
- Both the tailing and the journal reading now writes the lines to a channel
- Cleaned up the Describe and Collect functions.

### CODE REVIEW

**Comment by flyhard** [comment]
The reason for changing the showq processing also to be channel based is that calculating it on-the-fly during collection makes the service slower - and someone was to hammer the metrics endpoint it would go right through to the postfix process, which I'd rather not have.

**Comment by flyhard** [comment]
Fixed a problem with large queues. When the showq couldn't be processed within less than 10s Prometheus has a problem with it. 
The issue was that if we keep reseting the histogram (which we  have to) we cannot read meaningful data while we process from showq - and the lock was blocking reading the stats.

I ended up creating new histograms every time and replacing the old histogram as soon as  it was complete.

**Comment by danielgg-coding** [comment]
Is there any way to prevent reseting the histogram data reading from showq socket? 
Keep resetting make it hard to correctly show meaningful data on dashboards such as Grafana

**Comment by flyhard** [comment]
> Is there any way to prevent reseting the histogram data reading from showq socket?
> Keep resetting make it hard to correctly show meaningful data on dashboards such as Grafana

Sorry, the reset is needed because showq gives you a complete new state each time, and the only thing I can image just now is keeping the whole thing in memory. This might be fine for a few entries, but I have seen 10k+ messages in there, and that consumes a lot of memory. And a complete diff for that takes a lot of resources, I believe.

**Comment by BartVerc** [comment]
Thanks for the MR. The code base has changed significantly due to the implementation of #60. I will try to make time to look through your commits and pick the improvements. But I am closing this MR for now.

**Pull request closed without merging**
